name: SUSFS Kernel Builder

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu xz-utils flex bison

    - name: Configure SUSFS
      run: |
        echo "CONFIG_SUSFS=y" >> .config
        yes "" | make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig

    - name: Build kernel
      run: |
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

    - name: Upload kernel image
      uses: actions/upload-artifact@v4  # 关键修复点
      with:
        name: kernel-image
        path: arch/arm64/boot/Image.gz-dtb
